services:
  portfolio:
    image: simple-portfolio
    container_name: simple-portfolio-container
    ports:
      - "8080:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
